// ─── All destinations. Each entry becomes /destinations/<slug> ───
// Visa rules change often: confirm before quoting to a customer.

export const destinations = [
  {
    slug: "ladakh",
    name: "Ladakh",
    region: "india",
    img: "/images/ladakh.jpg",
    hero: "/images/ladakh-banner.jpg",
    duration: "5 Nights 6 Days",
    tagline: "High passes, blue lakes and quiet monasteries on the roof of India.",
    bestTime: "May to September",
    visa: "No visa needed. Permits for Nubra and Pangong arranged by us.",
    idealFor: "Adventure seekers, road-trippers, photographers",
    overview:
      "Ladakh is a cold desert of wide valleys, prayer flags and turquoise lakes set between the Himalaya and Karakoram. Our trip gives you time to acclimatise in Leh before crossing Khardung La into Nubra Valley and driving on to the changing blues of Pangong Lake.",
    highlights: [
      "Sunrise at Shanti Stupa and Leh Palace",
      "Double-humped camels in the Hunder sand dunes",
      "A night by Pangong Lake",
      "Thiksey and Diskit monasteries",
      "Crossing Khardung La and Chang La passes",
    ],
    itinerary: [
      { t: "Arrive in Leh", d: "Airport pickup and a full day of rest to acclimatise. Easy evening walk in Leh market." },
      { t: "Leh sightseeing", d: "Hall of Fame, Magnetic Hill, Gurudwara Pathar Sahib and the Sangam of the Indus and Zanskar." },
      { t: "Leh to Nubra Valley", d: "Drive over Khardung La to Nubra. Visit Diskit Monastery and the Hunder dunes." },
      { t: "Nubra to Pangong Lake", d: "Scenic drive via Shyok to Pangong. Evening by the lake, overnight in a lakeside camp." },
      { t: "Pangong to Leh", d: "Return over Chang La. Stop at Thiksey Monastery and Shey Palace on the way." },
      { t: "Departure", d: "Transfer to Leh airport with memories of the mountains." },
    ],
    inclusions: ["Hotels and camps with breakfast and dinner", "Private vehicle with driver", "Inner-line permits and environment fee", "Airport transfers"],
    exclusions: ["Flights", "Lunch and personal expenses", "Monument entry fees", "Travel insurance"],
  },
  {
    slug: "kerala",
    name: "Kerala",
    region: "india",
    img: "/images/kerala.jpg",
    duration: "4 Nights 5 Days",
    tagline: "Backwaters, tea hills and palm-lined villages at an easy pace.",
    bestTime: "September to March",
    visa: "No visa needed for Indian travellers.",
    idealFor: "Couples, families, slow travellers",
    overview:
      "Kerala moves at the pace of a houseboat. This trip takes you from the spice-scented tea estates of Munnar down to Alleppey, where you spend a night drifting through palm-fringed backwaters with meals cooked on board.",
    highlights: [
      "A night on a private houseboat in Alleppey",
      "Tea gardens and Eravikulam National Park in Munnar",
      "Kathakali and Kalaripayattu shows",
      "Fort Kochi's Chinese fishing nets",
      "Spice plantation walk",
    ],
    itinerary: [
      { t: "Arrive in Kochi, drive to Munnar", d: "Pickup from Kochi and a scenic drive past Cheeyappara waterfalls to Munnar." },
      { t: "Munnar sightseeing", d: "Eravikulam National Park, Mattupetty Dam, Echo Point and a tea museum visit." },
      { t: "Munnar to Alleppey houseboat", d: "Board your houseboat at noon and cruise the backwaters. Overnight on board." },
      { t: "Alleppey to Kochi", d: "Disembark after breakfast. Fort Kochi, Jew Town and the Chinese fishing nets." },
      { t: "Departure", d: "Transfer to Kochi airport or railway station." },
    ],
    inclusions: ["Hotels with breakfast", "Houseboat with all meals", "Private car with driver", "Pickup and drop"],
    exclusions: ["Flights and trains", "Entry tickets and show tickets", "Personal expenses", "Travel insurance"],
  },
  {
    slug: "meghalaya",
    name: "Meghalaya",
    region: "india",
    img: "/images/meghalaya.jpg",
    duration: "3 Nights 4 Days",
    tagline: "Living root bridges, crystal rivers and cloud-covered hills.",
    bestTime: "October to April",
    visa: "No visa or permit needed for Indian travellers.",
    idealFor: "Nature lovers, trekkers, families",
    overview:
      "Meghalaya, the abode of clouds, is a green plateau of waterfalls, caves and clear rivers. You stay in Shillong and explore Cherrapunji's root bridges and the glass-clear Umngot River at Dawki.",
    highlights: [
      "Double-decker living root bridge",
      "Boat ride on the clear Umngot River at Dawki",
      "Mawlynnong, one of Asia's cleanest villages",
      "Nohkalikai and Seven Sisters falls",
      "Mawsmai caves",
    ],
    itinerary: [
      { t: "Arrive in Guwahati, drive to Shillong", d: "Stop at Umiam Lake on the way. Evening at Police Bazaar." },
      { t: "Cherrapunji day trip", d: "Nohkalikai Falls, Mawsmai Cave, Seven Sisters Falls and Eco Park." },
      { t: "Dawki and Mawlynnong", d: "Boat ride on the Umngot River, the living root bridge at Riwai and Mawlynnong village." },
      { t: "Departure", d: "Drive back to Guwahati for your onward journey." },
    ],
    inclusions: ["Hotels with breakfast", "Private vehicle with driver", "Guwahati pickup and drop"],
    exclusions: ["Flights", "Boating and entry fees", "Personal expenses", "Travel insurance"],
  },
  {
    slug: "nepal",
    name: "Nepal",
    region: "international",
    img: "/images/nepal.jpg",
    duration: "5 Nights 6 Days",
    tagline: "Ancient stupas, lakeside Pokhara and Himalayan sunrises.",
    bestTime: "October to November and March to May",
    visa: "No visa needed for Indian citizens. Carry a passport or voter ID.",
    idealFor: "Families, pilgrims, first-time international travellers",
    overview:
      "Nepal pairs the temples and squares of the Kathmandu Valley with the calm of Pokhara, where the Annapurna range reflects in Phewa Lake. An easy first trip abroad with no visa hassle.",
    highlights: [
      "Boudhanath and Swayambhunath stupas",
      "Pashupatinath Temple",
      "Sunrise over the Annapurnas from Sarangkot",
      "Boating on Phewa Lake",
      "Bhaktapur Durbar Square",
    ],
    itinerary: [
      { t: "Arrive in Kathmandu", d: "Airport pickup, check in and evening at Thamel." },
      { t: "Kathmandu sightseeing", d: "Pashupatinath, Boudhanath, Swayambhunath and Kathmandu Durbar Square." },
      { t: "Kathmandu to Pokhara", d: "Scenic drive along the Trishuli river. Evening by Phewa Lake." },
      { t: "Pokhara sightseeing", d: "Sarangkot sunrise, Davis Falls, Gupteshwor Cave and boating on Phewa Lake." },
      { t: "Pokhara to Kathmandu", d: "Drive back and visit Bhaktapur Durbar Square on the way." },
      { t: "Departure", d: "Transfer to Kathmandu airport." },
    ],
    inclusions: ["Hotels with breakfast", "Private vehicle with driver", "Airport transfers", "Sightseeing as per itinerary"],
    exclusions: ["Flights", "Entry fees", "Personal expenses", "Travel insurance"],
  },
  {
    slug: "thailand",
    name: "Thailand",
    region: "international",
    visaFree: true,
    img: "/images/highlights-asia.jpg",
    hero: "/images/highlights-asia.jpg",
    duration: "4 Nights 5 Days",
    tagline: "Island hopping, golden temples and Bangkok's street food.",
    bestTime: "November to February",
    visa: "Visa-free entry for Indian passport holders. We confirm current rules before you book.",
    idealFor: "Couples, friends, first-time international travellers",
    overview:
      "Thailand is Asia's easiest escape: limestone islands off Phuket, glittering temples in Bangkok and food on every corner. This trip covers the Phi Phi islands and the best of Bangkok.",
    highlights: [
      "Phi Phi islands speedboat tour",
      "Wat Pho and the Grand Palace",
      "Chao Phraya river cruise with dinner",
      "Patong beach and Old Phuket Town",
      "Night markets and street food",
    ],
    itinerary: [
      { t: "Arrive in Phuket", d: "Airport pickup, check in and a free evening at Patong beach." },
      { t: "Phi Phi island tour", d: "Full-day speedboat tour to Maya Bay, Pileh Lagoon and Khai island with lunch." },
      { t: "Phuket to Bangkok", d: "Morning city tour of Phuket, then fly to Bangkok. Evening dinner cruise." },
      { t: "Bangkok temples", d: "Wat Pho, Wat Arun and the Grand Palace, then shopping at Pratunam." },
      { t: "Departure", d: "Transfer to Bangkok airport." },
    ],
    inclusions: ["Hotels with breakfast", "Phi Phi tour with lunch", "Dinner cruise", "Airport transfers on SIC basis"],
    exclusions: ["International and domestic flights", "Personal expenses", "Travel insurance"],
  },
  {
    slug: "azerbaijan",
    name: "Azerbaijan",
    region: "international",
    img: "/images/azerbaijan.jpg",
    duration: "4 Nights 5 Days",
    tagline: "The land of fire, where a walled old city meets flame-shaped towers.",
    bestTime: "April to June and September to October",
    visa: "e-Visa for Indian passport holders, processed by our team.",
    idealFor: "Couples, city lovers, short international breaks",
    overview:
      "Baku mixes a UNESCO-listed old city with glass skyscrapers and the Caspian seafront. Day trips take you to mud volcanoes, rock carvings and the green mountain town of Gabala.",
    highlights: [
      "Icherisheher, Baku's walled old city",
      "Flame Towers lit up at night",
      "Gobustan rock art and mud volcanoes",
      "Yanar Dag, the burning hillside",
      "Cable cars and lakes of Gabala",
    ],
    itinerary: [
      { t: "Arrive in Baku", d: "Airport pickup, check in and an evening walk along Baku Boulevard." },
      { t: "Baku city tour", d: "Old city, Maiden Tower, Shirvanshahs' Palace, Highland Park and the Flame Towers." },
      { t: "Gobustan and Absheron", d: "Gobustan rock art, mud volcanoes, Ateshgah fire temple and Yanar Dag." },
      { t: "Gabala day trip", d: "Tufandag cable car, Nohur Lake and the Seven Beauties waterfall." },
      { t: "Departure", d: "Transfer to Baku airport." },
    ],
    inclusions: ["Hotels with breakfast", "Tours with English-speaking guide", "Airport transfers", "e-Visa assistance"],
    exclusions: ["Flights", "Lunch and dinner", "Cable car tickets", "Travel insurance"],
  },
  {
    slug: "turkey",
    name: "Turkey",
    region: "international",
    img: "/images/turkey.jpg",
    duration: "6 Nights 7 Days",
    tagline: "Istanbul's domes, Cappadocia's balloons and a journey across two continents.",
    bestTime: "April to May and September to November",
    visa: "Sticker visa, or e-Visa if you hold a valid US, UK or Schengen visa.",
    idealFor: "Couples, history lovers, families",
    overview:
      "Turkey spans Europe and Asia. Start in Istanbul among mosques, bazaars and the Bosphorus, then fly to Cappadocia for fairy chimneys, cave hotels and a sunrise balloon ride.",
    highlights: [
      "Hagia Sophia and the Blue Mosque",
      "Bosphorus cruise",
      "Hot-air balloon over Cappadocia",
      "Grand Bazaar and Spice Bazaar",
      "A night in a cave hotel",
    ],
    itinerary: [
      { t: "Arrive in Istanbul", d: "Airport pickup and a free evening in Sultanahmet." },
      { t: "Istanbul old city", d: "Hagia Sophia, Blue Mosque, Topkapi Palace and the Grand Bazaar." },
      { t: "Bosphorus and Asian side", d: "Bosphorus cruise, Spice Bazaar and an evening in Kadıköy." },
      { t: "Fly to Cappadocia", d: "Short flight to Kayseri, transfer to your cave hotel in Göreme." },
      { t: "Cappadocia red tour", d: "Optional sunrise balloon, then Göreme Open Air Museum, Uçhisar and Pasabag." },
      { t: "Cappadocia to Istanbul", d: "Underground city at Derinkuyu, then fly back to Istanbul." },
      { t: "Departure", d: "Transfer to Istanbul airport." },
    ],
    inclusions: ["Hotels with breakfast", "Domestic flight Istanbul–Cappadocia", "Guided tours", "Airport transfers"],
    exclusions: ["International flights", "Balloon ride", "Lunch and dinner", "Travel insurance"],
  },
  {
    slug: "seychelles",
    name: "Seychelles",
    region: "international",
    visaFree: true,
    img: "/images/seychelles.jpg",
    duration: "5 Nights 6 Days",
    tagline: "Granite boulders, turquoise lagoons and beaches made for slow days.",
    bestTime: "April to May and October to November",
    visa: "Visitor's permit on arrival. Online travel authorisation needed before flying.",
    idealFor: "Honeymooners, beach lovers",
    overview:
      "The Seychelles are 115 islands in the Indian Ocean. You stay on Mahé and Praslin, with a day on La Digue, home to Anse Source d'Argent and its famous granite boulders.",
    highlights: [
      "Anse Source d'Argent on La Digue",
      "Vallée de Mai and its coco de mer palms",
      "Anse Lazio beach on Praslin",
      "Victoria market on Mahé",
      "Snorkelling in Sainte Anne Marine Park",
    ],
    itinerary: [
      { t: "Arrive on Mahé", d: "Airport pickup and check in. Evening on Beau Vallon beach." },
      { t: "Mahé island tour", d: "Victoria market, botanical garden, Mission Lodge viewpoint and Anse Takamaka." },
      { t: "Ferry to Praslin", d: "Catamaran ferry to Praslin. Afternoon at Anse Lazio." },
      { t: "La Digue day trip", d: "Cycle across La Digue to Anse Source d'Argent and Union Estate." },
      { t: "Praslin to Mahé", d: "Vallée de Mai in the morning, ferry back to Mahé." },
      { t: "Departure", d: "Transfer to Seychelles International Airport." },
    ],
    inclusions: ["Hotels with breakfast", "Inter-island ferries", "Airport and jetty transfers", "La Digue day trip"],
    exclusions: ["Flights", "Park entry fees", "Lunch and dinner", "Travel insurance"],
  },
  {
    slug: "georgia",
    name: "Georgia",
    region: "international",
    img: "/images/georgia.jpg",
    duration: "5 Nights 6 Days",
    tagline: "Mountain monasteries, wine valleys and the charm of old Tbilisi.",
    bestTime: "May to October",
    visa: "e-Visa for Indian passport holders. Visa-free with a valid US, UK or Schengen visa.",
    idealFor: "Couples, road-trippers, food and wine lovers",
    overview:
      "Georgia is a small country of big landscapes. Tbilisi's sulphur baths and balconied lanes lead to the Caucasus at Kazbegi and the vineyards of Kakheti, with warm hospitality all the way.",
    highlights: [
      "Gergeti Trinity Church below Mount Kazbek",
      "Old Tbilisi, Narikala Fortress and sulphur baths",
      "Ananuri fortress on the Military Highway",
      "Wine tasting in Kakheti and Sighnaghi",
      "Mtskheta, the ancient capital",
    ],
    itinerary: [
      { t: "Arrive in Tbilisi", d: "Airport pickup and an evening walk on Rustaveli Avenue." },
      { t: "Tbilisi city tour", d: "Narikala Fortress by cable car, sulphur baths, Bridge of Peace and Mtskheta." },
      { t: "Kazbegi day trip", d: "Georgian Military Highway via Ananuri and Gudauri to Gergeti Trinity Church." },
      { t: "Kakheti wine region", d: "Sighnaghi, Bodbe Monastery and a winery visit with tasting." },
      { t: "Free day in Tbilisi", d: "Shopping at Dry Bridge market or an optional Borjomi trip." },
      { t: "Departure", d: "Transfer to Tbilisi airport." },
    ],
    inclusions: ["Hotels with breakfast", "Private tours with driver", "Airport transfers", "Wine tasting"],
    exclusions: ["Flights", "Cable car and entry fees", "Lunch and dinner", "Travel insurance"],
  },
  {
    slug: "dubai",
    name: "Dubai",
    region: "international",
    img: "/images/dubai.jpg",
    duration: "4 Nights 5 Days",
    tagline: "Desert dunes, record-breaking skylines and souks full of gold.",
    bestTime: "November to March",
    visa: "UAE tourist e-Visa, processed by our team.",
    idealFor: "Families, shoppers, first-time international travellers",
    overview:
      "Dubai packs a lot into a short trip: the view from the Burj Khalifa, dune bashing in the desert, a dhow cruise along the creek and a day in Abu Dhabi at the Sheikh Zayed Grand Mosque.",
    highlights: [
      "At the Top, Burj Khalifa",
      "Desert safari with BBQ dinner",
      "Dhow cruise on Dubai Marina",
      "Sheikh Zayed Grand Mosque in Abu Dhabi",
      "Gold and spice souks in Deira",
    ],
    itinerary: [
      { t: "Arrive in Dubai", d: "Airport pickup and evening dhow cruise with dinner." },
      { t: "Dubai city tour", d: "Jumeirah Mosque, Burj Al Arab photo stop, souks and Burj Khalifa At the Top." },
      { t: "Desert safari", d: "Free morning. Afternoon dune bashing, camel ride and BBQ dinner with shows." },
      { t: "Abu Dhabi day trip", d: "Sheikh Zayed Grand Mosque and a Ferrari World or Louvre Abu Dhabi option." },
      { t: "Departure", d: "Transfer to Dubai airport." },
    ],
    inclusions: ["Hotels with breakfast", "Tours as per itinerary", "UAE visa", "Airport transfers"],
    exclusions: ["Flights", "Tourism Dirham fee", "Personal expenses", "Travel insurance"],
  },
  {
    slug: "singapore",
    name: "Singapore",
    region: "international",
    img: "/images/singapore.jpg",
    duration: "5 Nights 6 Days",
    tagline: "Garden city skylines, Sentosa beaches and the best hawker food.",
    bestTime: "February to April (pleasant all year)",
    visa: "Singapore e-Visa, applied through our authorised agent.",
    idealFor: "Families with kids, couples, food lovers",
    overview:
      "Singapore is clean, safe and full of things to do. See Gardens by the Bay light up, spend a day at Sentosa and Universal Studios, and eat your way through Chinatown and Little India.",
    highlights: [
      "Gardens by the Bay light show",
      "Universal Studios Singapore",
      "Night Safari",
      "Marina Bay Sands SkyPark",
      "Hawker centres in Chinatown",
    ],
    itinerary: [
      { t: "Arrive in Singapore", d: "Airport pickup, check in and evening at Clarke Quay." },
      { t: "City tour and Gardens by the Bay", d: "Merlion Park, Chinatown, Little India, then Gardens by the Bay at night." },
      { t: "Sentosa island", d: "Cable car, S.E.A. Aquarium and the Wings of Time show." },
      { t: "Universal Studios", d: "Full day at Universal Studios Singapore." },
      { t: "Night Safari", d: "Free day for shopping on Orchard Road, then the Night Safari." },
      { t: "Departure", d: "Transfer to Changi airport. Allow time for the Jewel waterfall." },
    ],
    inclusions: ["Hotels with breakfast", "Tickets as per itinerary", "Singapore visa", "Airport transfers"],
    exclusions: ["Flights", "Lunch and dinner", "Personal expenses", "Travel insurance"],
  },
];

export const getDestination = (slug) => destinations.find((d) => d.slug === slug);
export const bySlugs = (slugs) => slugs.map(getDestination).filter(Boolean);
export const destHref = (d) => `/destinations/${d.slug}`;
